{
 "title": "Ceph RadosGW",
 "tags": [ "rgw" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "owner",
    "label": "Owner",
    "query": {
     "query": "label_values(ceph_radosgw_quota_user_enabled{cluster=\"$cluster\"}, owner)"
    }
   },
   {
    "name": "bucket",
    "label": "Bucket",
    "query": {
     "query": "label_values(ceph_radosgw_bucket_size_kb{cluster=\"$cluster\", owner=~\"$owner\"}, bucket)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total S3 Objects in cluster",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(ceph_radosgw_bucket_num_objects{cluster=\"$cluster\"})",
     "legendFormat": "Total objects"
    }
   ]
  },
  {
   "title": "Total S3 cluster used size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "sum(ceph_radosgw_user_size_kb{cluster=\"$cluster\"})",
     "legendFormat": "Total size"
    }
   ]
  },
  {
   "title": "Objects Num per Bucket",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ceph_radosgw_bucket_num_objects{cluster=\"$cluster\",bucket=~\"$bucket\"}",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "title": "Quota User Max Objects per Bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "ceph_radosgw_quota_bucket_max_objects{cluster=\"$cluster\",owner=~\"$owner\"}",
     "legendFormat": "{{ owner }}"
    }
   ]
  },
  {
   "title": "Bucket Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "ceph_radosgw_bucket_size_kb{cluster=\"$cluster\",bucket=~\"$bucket\"}",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "title": "Quota Bucket Max Size",
   "type": "timeseries",
   "description": "-1 = unlimited",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "ceph_radosgw_quota_bucket_max_size_kb{cluster=\"$cluster\",owner=~\"$owner\"}",
     "legendFormat": "{{ owner }}"
    }
   ]
  },
  {
   "title": "User Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "ceph_radosgw_user_size_kb{cluster=\"$cluster\",owner=~\"$owner\"}",
     "legendFormat": "{{ owner }}"
    }
   ]
  },
  {
   "title": "Quota User Max Size",
   "type": "timeseries",
   "description": "-1 = unlimited",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "ceph_radosgw_quota_user_max_size_kb{cluster=\"$cluster\",owner=~\"$owner\"}",
     "legendFormat": "{{ owner }}"
    }
   ]
  },
  {
   "title": "User Num Objects",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ceph_radosgw_user_num_objects{cluster=\"$cluster\",owner=~\"$owner\"}",
     "legendFormat": "{{ owner }}"
    }
   ]
  },
  {
   "title": "Quota User Max Obejcts ",
   "type": "timeseries",
   "description": "-1 = unlimited",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ceph_radosgw_quota_user_max_objects{cluster=\"$cluster\",owner=~\"$owner\"}",
     "legendFormat": "{{ owner }}"
    }
   ]
  },
  {
   "title": "Bucket Shards Num",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceph_radosgw_bucket_num_shards{cluster=\"$cluster\",bucket=~\"$bucket\"}",
     "legendFormat": "{{ bucket }}"
    }
   ]
  }
 ]
}