apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-radosgw-exporter
  labels:
    app.kubernetes.io/name: prometheus-radosgw-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-radosgw-exporter
  endpoints:
  - honorLabels: true
    interval: 90s
    path: /metrics
    port: http
    scheme: http
    scrapeTimeout: 60s
  jobLabel: prometheus-radosgw-exporter
