name: image

on:
  release:
    types:
      - published

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - name: Install QEMU static binaries
        uses: docker/setup-qemu-action@v3.0.0

      - name: Configure Buildkit
        uses: docker/setup-buildx-action@v3.0.0

      - name: Checkout project
        uses: actions/checkout@v4

      - name: Authenticate with Quay.io
        uses: docker/login-action@v3.0.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Generate image tag
        id: image_tag
        run: |
          echo tag=$(echo ${{ github.event.release.tag_name }} | sed 's/^v//') >> $GITHUB_OUTPUT

      - name: Build image
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            quay.io/tadas/radosgw-exporter:latest
            quay.io/tadas/radosgw-exporter:${{ steps.image_tag.outputs.tag }}
