---
    name: release

    on:
      push:
        tags:
          - '*'

    jobs:
      release:
        runs-on:
          - ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
              # It is required for the changelog to work correctly.
              fetch-depth: 0

          - name: Setup Go
            uses: actions/setup-go@v5
            with:
              go-version-file: go.mod

          - name: Release
            uses: goreleaser/goreleaser-action@v6
            with:
              args: release --clean
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      image:
        runs-on: ubuntu-latest
        steps:
          - name: Install QEMU static binaries
            uses: docker/setup-qemu-action@v3.2.0

          - name: Configure Buildkit
            uses: docker/setup-buildx-action@v3.8.0

          - name: Checkout project
            uses: actions/checkout@v4

          - name: Authenticate with Quay.io
            uses: docker/login-action@v3.3.0
            with:
              registry: quay.io
              username: ${{ secrets.QUAY_USERNAME }}
              password: ${{ secrets.QUAY_ROBOT_TOKEN }}

          - name: Generate image tag
            id: image_tag
            run: |
              echo tag=$(echo ${{ github.ref_name }} | sed 's/^v//') >> $GITHUB_OUTPUT

          - name: Build image
            uses: docker/build-push-action@v6.10.0
            with:
              context: .
              cache-from: type=gha
              cache-to: type=gha,mode=max
              push: true
              platforms: |
                linux/amd64
                linux/arm64
              tags: |
                quay.io/tadas/radosgw-exporter:latest
                quay.io/tadas/radosgw-exporter:${{ steps.image_tag.outputs.tag }}
  